databases:
  - name: Bookme-app-db
    databaseName: bookme_app_db
    user: tibi
    plan: free
    region: frankfurt

services:
  - type: web
    name: bookme-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Bookme-app-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    plan: free
  - type: redis
    name: redis-bookme
    region: frankfurt
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
